import { Anchor, Box, Container, Group, Text } from '@mantine/core';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { publicApiFetch } from '@/lib/api';
import type { Report } from '@/types';
import { ReportView } from '@/components/report/ReportView';

export const dynamic = 'force-dynamic';

type PageProps = {
  params: Promise<{ shareToken: string }>;
};

export default async function SharePage({ params }: PageProps) {
  const { shareToken } = await params;

  let report: Report;
  try {
    const payload = await publicApiFetch<{ report: Report }>(`/api/share/${shareToken}`);
    report = payload.report;
  } catch {
    notFound();
  }

  return (
    <Box className="app-canvas" mih="100vh">
      <Box py="sm" px="xl" className="app-rail">
        <Group gap="xs">
          <Text size="sm" c="dark.1">
            Generated by CodeMap ·
          </Text>
          <Anchor component={Link} href="/" size="sm">
            Analyze your own repo
          </Anchor>
        </Group>
      </Box>
      <Container size="xl" py="xl">
        <ReportView report={report} publicView />
      </Container>
    </Box>
  );
}
